exclude: ["README.md", "template.md"]
highlighter: rouge

title: "CTF Writeups"
author:
  name: Garfield Yang
  email: darkpanda8123@gmail.com
  github: garfield8123

remote_theme: sighingnow/jekyll-gitbook

url: "https://garfield8123.github.io"
baseurl: "/CTFWriteups"

markdown: kramdown
kramdown:
  input: GFM
