exclude: ["README.md", "template.md"]
highlighter: rouge


title : CTF Writeups
tagline: Site containing garfield8123 CTF Writeups
author :
	name : Garfield Yang
	github : garfield8123
   	feedburner : nil

production_url : http://garfield8123.github.io/CTFWriteups
BASE_PATH : http://garfield8123.github.io/CTFWriteups	

markdown: kramdown
