exclude: ["README.md", "template.md"]
highlighter: rouge

title: "CTF Writeups"
author:
  name: Garfield Yang
  email: darkpanda8123@gmail.com
  github: garfield8123

remote_theme: sighingnow/jekyll-gitbook

syntax_highlighter_style: colorful

toc:
    enabled: true
    h_min: 1
    h_max: 3

markdown: kramdown
kramdown:
  input: GFM
