title : Jekyll Bootstrap
tagline: Site Tagline
author :
	  name : Name Lastname
	  email : blah@email.test
	  github : username
	  twitter : username
	  feedburner : feedname

production_url : http://garfield8123.github.io/CTFWriteups
BASE_PATH : http://garfield8123.github.io/CTFWriteups	

markdown: kramdown
